name = "LambdaLLG"
uuid = "e49eaffb-1ff4-4058-b8bd-8b5ecf266929"
authors = ["freyes"]
version = "1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DifferentialEquations = "7.17.0"
LinearAlgebra = "1.11.0"
